# Generated by Django 3.1.5 on 2021-01-20 08:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default=datetime.datetime(2021, 1, 20, 8, 24, 19, 351229, tzinfo=utc), max_length=100),
            preserve_default=False,
        ),
    ]
